### ISSUE TITLE
Lot of slides

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-website#10]
Then we have a lot of slides. Is it too much?
Could the list of libraries be displayed at once without slide?

**Comment by bunsenstraat** [comment]
no more slides, except for the photos. check the new lib and plugin layout. see if that's ok.

**Comment by yann300** [comment]
Now the limit between "Extend" and "Tools for developer" is not very clear.
I didn't meant that you should remove all the slides, just some of them.
Having slides for the "Extend" was I think ok.
reopening it

**Comment by bunsenstraat** [comment]
slides are back. now with transparent background and lighter icons, I changed them in the svg and Sketch.
