### ISSUE TITLE
Github link is pointed to archived project

### ISSUE THREAD

**Issue by mayankkholia** [ethereum/remix-website#39]
Github link in homepage points to _https://github.com/ethereum/remix_ (archived), whereas it should point to _https://github.com/ethereum/remix-project_

**Comment by simplysabir** [comment]
Hey, Can i work on this issue?

So, Basically i have to change the link in the footer right?

**Comment by LianaHus** [comment]
fixed by https://github.com/ethereum/remix-website/pull/41
