### ISSUE TITLE
Remix workshop

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-website#8]
In the workshop section (or maybe even on the top bar), we should say that we are giving workshops and ready to answer requests.
cc @ryestew

**Comment by bunsenstraat** [comment]
I need some more info. I've added a text in the section. But it's not very concrete.

**Comment by yann300** [comment]
Could you add something an icon or action in the top bar to invite people to contact us for having a workshop?
cc @ryestew @bunsenstraat  what do you think?

**Comment by ryestew** [comment]
On the top bar @yann300 do you mean like to the right or left of the "chat with us" & "Remix IDE" on the very top of the site?  Something like "Remix chez vous"  or "Remix-a-talk" or "Remix Mixers" which would pop down to the Workshop section.

Here's some text to replace the current text about workshops:

The Remix project team is giving workshops both about Remix and more general introductions to blockchains and their uses.  We tailor our presentations to the technical knowledge of your group and we try to give entertaining talks. Reach out to us by e-mail or chat with us on one of our gitter channels.

**Comment by yann300** [comment]
Yes this is what I meant

**Comment by bunsenstraat** [comment]
done
